language: python

python:
 - 2.7

addons:
  apt:
    sources:
      - deadsnakes
    packages:
      - python2.4
      - python2.5
      - python2.6
      - python3.1
      - pypy

env:
 - TOXENV=py24

install:
 - if [[ $(echo "$TOXENV" | egrep -c "(py2[45]|py31)") != 0 ]]; then pip install virtualenv==1.7.2 tox==1.3; fi;
 - if [[ $(echo "$TOXENV" | egrep -c "(py2[45]|py31)") == 0 ]]; then pip install tox; fi;

script:
 - tox

notifications:
  email:
    - matt@sivel.net
