---
language: c

script:
 - curl -s http://www.python.org/ftp/python/2.4.6/Python-2.4.6.tar.bz2 | tar xj
 - cd Python-2.4.6
 - ./configure --prefix=$HOME/virtualenv/python2.4 > /dev/null 2>&1 && make > /dev/null 2>&1 && make install > /dev/null 2>&1
 - $HOME/virtualenv/python2.4/bin/python -V
 - $HOME/virtualenv/python2.4/bin/python speedtest_cli.py

---
language: python

python:
 - 2.7
 - 3.3

install:
  - pip install .
  - pip install pep8 pyflakes

script:
  - if [[ $TRAVIS_PYTHON_VERSION == '2.7' ]]; then pep8 --show-source speedtest_cli.py; fi
  - if [[ $TRAVIS_PYTHON_VERSION == '2.7' ]]; then pyflakes speedtest_cli.py; fi
  - python speedtest_cli.py

notifications:
  email:
    - matt@sivel.net
