language: python

python:
 - 2.7

install:
  - pip install .
  - pip install pep8 pyflakes

script:
  - pep8 --show-source speedtest_cli.py
  - pyflakes speedtest_cli.py

notifications:
  email:
    - matt@sivel.net
